/**
 * Story page data generated by the LLM.
 */
export interface StoryScriptPage {
  pageNumber: number;
  textEn: string;
  summaryEn?: string;
}

/**
 * Result structure for the generated story script.
 */
export interface StoryScriptResult {
  titleEn: string;
  synopsisEn?: string;
  pages: StoryScriptPage[];
}

/**
 * Translation page data for the story.
 */
export interface TranslationPage {
  pageNumber: number;
  textZh: string;
  notesZh?: string;
}

/**
 * Result structure for the translated story.
 */
export interface TranslationResult {
  titleZh: string;
  synopsisZh?: string;
  pages: TranslationPage[];
}

/**
 * Vocabulary entry extracted from the story.
 */
export interface VocabularyEntry {
  word: string;
  partOfSpeech: string;
  definitionEn: string;
  definitionZh: string;
  exampleSentence: string;
  exampleTranslation: string;
  cefrLevel?: string;
}

/**
 * Result structure for the vocabulary extraction.
 */
export interface VocabularyResult {
  entries: VocabularyEntry[];
}

/**
 * Payload passed into the story generation orchestrator.
 */
export interface StoryGenerationPayload {
  storyId: string;
  theme: string;
  tone: string;
  ageRange: string;
  regenerate?: boolean;
}

/**
 * Token usage for a chat completion call.
 */
export interface ChatCompletionUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

/**
 * Standard result structure returned from the OpenAI adapter.
 */
export interface ChatCompletionResult<T> {
  data: T;
  usage?: ChatCompletionUsage;
}

/**
 * Adapter interface describing the minimal surface the orchestrator depends on.
 * Implemented structurally by OpenAIClientAdapter; tests can implement this interface.
 */
export interface OpenAIAdapter {
  createChatCompletion<T = unknown>(params: unknown, retryCount?: number): Promise<ChatCompletionResult<T>>;
}